# Generated by Django 5.2.1 on 2025-11-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_insumo_remove_producto_imagen_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='origen',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('web', 'Sitio Web'), ('otro', 'Otro')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='pago_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myApp.orden')),
            ],
        ),
    ]
