# Generated by Django 5.2.1 on 2025-11-30 22:17

import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_orden_origen_orden_pago_estado_ordenimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to=myApp.models.producto_imagen_path),
        ),
    ]
