# Generated by Django 5.2.1 on 2025-12-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_productoimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('insumo', 'Insumo')], default='producto', max_length=20),
        ),
    ]
