# Generated by Django 5.2.1 on 2025-12-01 06:12

import django.db.models.deletion
import django.utils.timezone
import myApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='pago_estado',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.AddField(
            model_name='orden',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='contacto',
            field=models.CharField(blank=True, default='', help_text='Email / teléfono / red social', max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_necesaria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='plataforma',
            field=models.CharField(default='pagina web', max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.producto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='token',
            field=models.CharField(default=myApp.models.generate_token, editable=False, max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenimagen',
            name='imagen',
            field=models.ImageField(upload_to='ordenes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.producto'),
        ),
    ]
