# Generated by Django 5.2.1 on 2025-12-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_orden_fecha_remove_orden_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
