# Generated by Django 5.2.1 on 2025-12-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_carritoitem_carrito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'insumo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.categoria'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
