# Generated by Django 5.2.1 on 2025-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_insumo_options_insumo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-creado'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenitem',
            options={'verbose_name': 'Ítem de orden', 'verbose_name_plural': 'Ítems de orden'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad pedida'),
        ),
    ]
