# Generated by Django 5.2.1 on 2025-12-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_orden_options_alter_ordenitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos/'),
        ),
    ]
