# Generated by Django 6.0 on 2025-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_insumo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='contacto',
        ),
        migrations.AddField(
            model_name='orden',
            name='contacto_tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('presencial', 'Presencial'), ('web', 'Sitio Web'), ('otros', 'Otros')], default='whatsapp', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='contacto_valor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
